### ISSUE TITLE
Joseph Fullop

### ISSUE THREAD

**Issue by brock** [ncsa/issues#1]
Joseph @fullop has been added to @ncsa/staff 

Does he need to be added to a team or do we need to create a new team?
https://github.com/orgs/ncsa/teams

@fullop would you mind adding a picture to your profile? :construction: 
https://github.com/settings/profile

**Comment by shivgori** [comment]
please write proper steps to use bro_meterpreter plugin

**Comment by brock** [comment]
@shivgori You'll get a faster response if you create an issue over on that repo: https://github.com/ncsa/bro_meterpreter/issues
