### ISSUE TITLE
Security team repository permissions

### ISSUE THREAD

**Issue by JustinAzoff** [ncsa/issues#3]
Somehow we only ended up as admins of the nagios-plugins repository and not all of the other ones:

![screen shot 2016-04-15 at 4 15 49 pm](https://cloud.githubusercontent.com/assets/65812/14573837/7fd5c728-0325-11e6-8c44-3de9ad83ff73.png)

Can you make it so we have full access to all of our repositories?

**Comment by brock** [comment]
Thanks for pointing this out @JustinAzoff. I've updated privileges of those repos to Admin. I looked at the options we have for Teams, but it looks like there isn't a built-in way to set the default permissions for any repos that a Github Team creates. I'm not certain on this, but it seems like you would create a new repo and only have Write permission. If you need it bumped up to Admin, for now it looks like the only option is to leave a message here and we'll increase it for you.

Is there a reason why we couldn't drop this down to Write for each of the repos?

**Comment by JustinAzoff** [comment]
There were 2 issues I noticed with missing Admin permissions, but there may have been more.

I wasn't able to edit any of the repository properties like the description.

I wasn't able to enable Travis-CI on bhr-site.  I don't think this needs admin permissions to work moving forward now that it is enabled.

**Comment by brock** [comment]
Thanks @JustinAzoff Those are good points. I think I'll send a help ticket to Github so they are aware. I'll change the settings back to Write, but I'll leave you as Admin since you are the Team Maintainer.
