### ISSUE TITLE
I am a young researcher and I would like to be able to contribute.

### ISSUE THREAD

**Issue by joelibaceta** [ncsa/issues#9]
Please consider adding me to the organization

Github username : joelibaceta

**Comment by robkooper** [comment]
This is the organization associated with https://ncsa.illinois.edu/ and we use it to keep our open source projects. People associated with the organization are either employees, or students.

Do you have any specific projects you would like to contribute to? If so we can talk to the maintainer of the software and they can add you as an external collaborator.
